grpc:
  # The port on which the gRPC server will listen
  port: 9090

# api-related fields
http:
  # The port on which the API will be exposed (default:3001)
  port: 8080

  # Enable/disable development CORS
  dev-cors: true

  # Allowed hosts for HTTP API development CORS
  dev-cors-host: "*"

# Control what to be logged using format "module=level,module=level"; `*` means all other modules
logging: "*=info"

network:
  name: "sapphire testnet"
  genesis-time: "2020-01-10T00:00:00Z"